INTENSITY_DATA_LANGUAGE = "hun"

INTENSITY_ZONE0_NAME = "Zone 0" if INTENSITY_DATA_LANGUAGE == "eng" else "Zóna 0"
INTENSITY_ZONE0_DESCRIPTION = "No Zone" if INTENSITY_DATA_LANGUAGE == "eng" else "Nincs Zóna"

INTENSITY_ZONE1_NAME = "Zone 1" if INTENSITY_DATA_LANGUAGE == "eng" else "Zóna 1"
INTENSITY_ZONE1_DESCRIPTION = "Very easy" if INTENSITY_DATA_LANGUAGE == "eng" else "Nagyon könnyű"

INTENSITY_ZONE2_NAME = "Zone 2" if INTENSITY_DATA_LANGUAGE == "eng" else "Zóna 2"
INTENSITY_ZONE2_DESCRIPTION = "Easy" if INTENSITY_DATA_LANGUAGE == "eng" else "Könnyű"

INTENSITY_ZONE3_NAME = "Zone 3" if INTENSITY_DATA_LANGUAGE == "eng" else "Zóna 3"
INTENSITY_ZONE3_DESCRIPTION = "Medium" if INTENSITY_DATA_LANGUAGE == "eng" else "NKözepes"

INTENSITY_ZONE4_NAME = "Zone 4" if INTENSITY_DATA_LANGUAGE == "eng" else "Zóna 4"
INTENSITY_ZONE4_DESCRIPTION = "Hard" if INTENSITY_DATA_LANGUAGE == "eng" else "Nehéz"

INTENSITY_ZONE5_NAME = "Zone 5" if INTENSITY_DATA_LANGUAGE == "eng" else "Zóna 5"
INTENSITY_ZONE5_DESCRIPTION = "Very hard" if INTENSITY_DATA_LANGUAGE == "eng" else "Nagyon nehéz"

INTENSITY_ZONE0_WEIGHT_FACTOR = 0
INTENSITY_ZONE1_WEIGHT_FACTOR = 1
INTENSITY_ZONE2_WEIGHT_FACTOR = 2
INTENSITY_ZONE3_WEIGHT_FACTOR = 3
INTENSITY_ZONE4_WEIGHT_FACTOR = 4
INTENSITY_ZONE5_WEIGHT_FACTOR = 5
